# Generated by Django 5.2.15 on 2026-07-06 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_business_name', models.CharField(help_text='Legal name of the business entity.', max_length=255)),
                ('vat_tax_number', models.CharField(help_text='Verified VAT / Tax Identification Number.', max_length=100)),
                ('payment_terms', models.CharField(choices=[('net_30', 'Net-30'), ('net_60', 'Net-60')], default='net_30', help_text='Pre-negotiated payment terms.', max_length=20)),
                ('discount_tier', models.CharField(choices=[('tier_1', 'Tier 1 (10% off)'), ('tier_2', 'Tier 2 (15% off)')], default='tier_1', help_text='Assigned contract discount tier.', max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=50000.0, help_text='Pre-approved credit line limit.', max_digits=12)),
                ('credit_used', models.DecimalField(decimal_places=2, default=0.0, help_text='Current outstanding balance against the credit line.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='company_profile',
            field=models.OneToOneField(blank=True, help_text='The corporate profile associated with this B2B user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='users.companyprofile'),
        ),
    ]
