# Generated by Django 5.2.15 on 2026-07-01 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('d2c_single', 'D2C Single Order'), ('d2c_subscription', 'D2C Subscription Order'), ('b2b_wholesale', 'B2B Wholesale Order')], default='d2c_single', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('packed', 'Packed'), ('dispatched', 'Dispatched'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total value of the order.', max_digits=12)),
                ('shipping_address', models.TextField(help_text='Full shipping destination address.')),
                ('inventory_decremented', models.BooleanField(default=False, help_text='Flag to ensure stock is only decremented once for this order.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(blank=True, help_text='The subscription that generated this order, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='subscriptions.subscription')),
                ('user', models.ForeignKey(help_text='The customer or B2B client placing the order.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, help_text='Historical price per item unit at the time of order placement.', max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('pad_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.padcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='WholesaleInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('vat_number', models.CharField(blank=True, help_text='Custom Tax/VAT registration identifier.', max_length=50)),
                ('billing_terms', models.CharField(choices=[('net_15', 'Net-15'), ('net_30', 'Net-30'), ('net_45', 'Net-45'), ('net_60', 'Net-60')], default='net_30', max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=20.0, help_text='Tax or VAT percentage (e.g. 20.00).', max_digits=5)),
                ('pdf_status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('pdf_file_path', models.CharField(blank=True, help_text='Path or URL to the generated invoice PDF.', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(help_text='The wholesale order this invoice is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_invoice', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
