# Generated by Django 5.2.15 on 2026-07-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', help_text='The tracking payment status of B2B Wholesale Invoice.', max_length=20),
        ),
    ]
