# Generated by Django 5.2.15 on 2026-07-01 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='The associated ID from Stripe Billing.', max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='active', help_text='Current billing/delivery cycle status.', max_length=20)),
                ('delivery_interval_days', models.PositiveIntegerField(default=28, help_text='Interval in days between recurring shipments.')),
                ('next_delivery_date', models.DateField(blank=True, help_text='The next planned delivery shipment date.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kit_product', models.ForeignKey(help_text='The base kit configuration metadata for this subscription.', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='products.kitproduct')),
                ('user', models.ForeignKey(help_text='The customer who owns this subscription.', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='The quantity of this specific pad component included in the package.')),
                ('pad_component', models.ForeignKey(help_text='The pad component type selected.', on_delete=django.db.models.deletion.PROTECT, related_name='subscription_items', to='products.padcomponent')),
                ('subscription', models.ForeignKey(help_text='The parent subscription.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'Subscription Item',
                'verbose_name_plural': 'Subscription Items',
                'unique_together': {('subscription', 'pad_component')},
            },
        ),
    ]
