# Generated by Django 5.2.15 on 2026-07-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KitProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the kit (e.g. Home Essential Kit).', max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what the kit contains.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Pricing for one-off purchase or per delivery cycle.', max_digits=10)),
                ('max_components', models.PositiveIntegerField(default=10, help_text='The exact total quantity of customizable components included in this kit.')),
                ('is_subscription_only', models.BooleanField(default=False, help_text='Designates if this kit can only be purchased as a subscription.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kit Product',
                'verbose_name_plural': 'Kit Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PadComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the pad component (e.g. Regular Pad).', max_length=100, unique=True)),
                ('component_type', models.CharField(choices=[('gym_pad', 'Gym Pad'), ('regular_pad', 'Regular Pad'), ('night_pad', 'Night Pad'), ('panty_liner', 'Panty Liner')], default='regular_pad', max_length=50)),
                ('stock_level', models.PositiveIntegerField(default=0, help_text='Current available inventory level.')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, help_text='Inventory level that triggers a low stock alert.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pad Component',
                'verbose_name_plural': 'Pad Components',
                'ordering': ['name'],
            },
        ),
    ]
