# Generated by Django 5.2.15 on 2026-07-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='padcomponent',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Wholesale price per unit for bulk B2B invoices.', max_digits=10),
        ),
    ]
